plugins {
    id 'org.omegat.module'
}

dependencies {
    compileOnly(project.rootProject)
    if (providedCoreLibsDir.directory) {
        compileOnly fileTree(dir: providedCoreLibsDir, includes: ['**/jspecify-*.jar', '**/flatlaf*.jar'])
    } else {
        compileOnly(libs.flatlaf) { artifact { classifier = "no-natives" } }
        compileOnly(libs.jspecify)
    }
    testImplementation(testFixtures(project.rootProject))
    testImplementation(libs.commons.io)
}
